version: "3.4"

services:
  backend:
    restart: unless-stopped
    container_name: backend
    depends_on:
      - local-database
    image: backend
    user: root
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - type: bind
        source: ./backend/
        target: /backend/
    ports:
      - target: 8000
        published: 8000
    working_dir: /backend
    networks:
      - project

  local-database:
    image: debezium/postgres
    restart: always
    container_name: local-database
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432
    volumes:
      - database:/var/lib/postgresql/data:Z
      - ./docker-scripts/local-database.sql:/docker-entrypoint-initdb.d/local-database.sql
    networks:
      - project

  frontend:
    restart: unless-stopped
    container_name: frontend
    image: frontend
    user: root
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - type: bind
        source: ./frontend/public
        target: /frontend/public
      - type: bind
        source: ./frontend/src
        target: /frontend/src
    ports:
      - target: 3000
        published: 3000
    networks:
      - project

volumes:
  database:

networks:
  project:
